changelog:
  catagories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting new features :tada:
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
